export const actionTypes = {
  GET_CLIENT_LIST_REQUEST: 'GET_CLIENT_LIST_REQUEST',
  GET_CLIENT_LIST_SUCCESS: 'GET_CLIENT_LIST_SUCCCESS',
  GET_CLIENT_LIST_ERROR: 'GET_CLIENT_LIST_ERROR',
  GET_CLIENT_LIST: 'GET_CLIENT_LIST',
  SET_CLIENT_LIST: 'SET_CLIENT_LIST',
  SET_CLIENT_LIST_ERROR_MESSAGE: 'SET_CLIENT_LIST_ERROR_MESSAGE',
};

export const clientListErrorMessage = 'idiot';
